package entity

var tagMapping = map[string]string{
	"politics":                              "politics",
	"environment":                           "environment",
	"society":                               "society",
	"culture":                               "culture",
	"sport":                                 "sport",
	"business":                              "business",
	"unions":                                "society",
	"travel":                                "society",
	"socialism":                             "politics",
	"pablo iglesias":                        "politics",
	"pedro sánchez":                         "politics",
	"podemos":                               "politics",
	"protest":                               "society",
	"francisco franco":                      "politics",
	"rape and sexual assault":               "society",
	"eta":                                   "society",
	"extreme weather":                       "environment",
	"flooding":                              "environment",
	"natural disasters and extreme weather": "environment",
	"catalonia":                             "politics",
	"air pollution":                         "environment",
	"kim jong-un":                           "politics",
	"donald trump":                          "politics",
	"animal welfare":                        "environment",
	"climate change":                        "environment",
	"theatre":                               "culture",
	"brexit":                                "politics",
	"migration":                             "society",
	"housing":                               "society",
	"communities":                           "society",
	"music":                                 "culture",
	"opera":                                 "culture",
	"cycling":                               "sport",
	"film":                                  "culture",
	"animals":                               "environment",
	"wildlife":                              "environment",
	"marine life":                           "environment",
	"fishing":                               "environment",
}
